name: Setup
on:
  workflow_dispatch:

env:
  SERVICE_NAME: serverless-nasa-test

jobs:
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.3.0
        with:
          project_id: ${{ secrets.PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          export_default_credentials: true

      - name: Deploy App on Cloud RUN
        run: |
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --image=docker.io/${{ secrets.DOCKER_USERNAME }}/serverless-nasa:v1 \
            --allow-unauthenticated \
            --service-account=${{ secrets.SERVICE_ACCOUNT }} \
            --max-instances=10 \
            --set-secrets=API_KEY=API_KEY:1 \
            --cpu-boost \
            --region=${{ secrets.REGION }} \
            --project=${{ secrets.PROJECT_ID }}
