name: Pipeline
on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:

env:
  SERVICE_NAME: serverles-nasa
  IMAGE: ${{ secrets.DOCKER_USERNAME }}/serverles-nasa:v${{github.run_number}}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile
          push: true
          tags: ${{ env.IMAGE }}

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.3.0
        with:
          project_id: ${{ secrets.PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          export_default_credentials: true

      - name: Deploy App on Cloud RUN
        run: |
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --image=docker.io/${{ env.IMAGE }} \
            --region=${{ secrets.REGION }} \
            --project=${{ secrets.PROJECT_ID }} \
            && gcloud run services update-traffic ${{ env.SERVICE_NAME }} --to-latest
